package com.example.gdtcontrol

import android.graphics.Bitmap
import androidx.compose.foundation.Image
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.PaddingValues
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.navigationBarsPadding
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.text.KeyboardActions
import androidx.compose.foundation.text.KeyboardOptions
import androidx.compose.material3.Button
import androidx.compose.material3.Icon
import androidx.compose.material3.Text
import androidx.compose.material3.TextField
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.asImageBitmap
import androidx.compose.ui.res.painterResource
import androidx.compose.ui.text.input.ImeAction
import androidx.compose.ui.text.input.KeyboardType
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.unit.dp
import androidx.core.text.isDigitsOnly
import androidx.lifecycle.viewModelScope
import com.google.zxing.qrcode.QRCodeWriter
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch


@Composable
fun ProductGeneratorScreen(viewModel: ViewModel) {
    val state = viewModel.state
    val isFormVisible = viewModel.isFormVisible

    var qrCodeGenerated by remember { mutableStateOf<Bitmap?>(null) }
    var showError by remember { mutableStateOf(false) }

    // Restablecer el formulario al ingresar a la pantalla
    LaunchedEffect(Unit) {
        viewModel.resetForm()
        qrCodeGenerated = null
    }

    Box(modifier = Modifier.fillMaxSize(), contentAlignment = Alignment.Center) {
        if (qrCodeGenerated != null) {
            Image(
                bitmap = qrCodeGenerated!!.asImageBitmap(),
                contentDescription = "",
                modifier = Modifier.size(200.dp)
            )
        } else if (isFormVisible) {
            LazyColumn(
                horizontalAlignment = Alignment.CenterHorizontally,
                modifier = Modifier
                    .fillMaxSize()
                    .padding(bottom = 16.dp)
                    .navigationBarsPadding(),
                contentPadding = PaddingValues(16.dp),
                verticalArrangement = Arrangement.spacedBy(8.dp)
            ) {
                item {
                    Text(text = "Generador de Qr code", textAlign = TextAlign.Center)
                }
                item {
                    Icon(
                        painter = painterResource(id = R.drawable.qr),
                        contentDescription = "",
                        modifier = Modifier.size(100.dp)
                    )
                }
                item {
                    Text(text = "Nombre de producto")
                    TextField(
                        value = state.name,
                        onValueChange = { viewModel.onNameChange(it) },
                        keyboardOptions = KeyboardOptions.Default.copy(
                            imeAction = ImeAction.Next
                        )
                    )
                }
                item {
                    Text(text = "Descripción")
                    TextField(
                        value = state.description,
                        onValueChange = { viewModel.onDescriptionChange(it) },
                        keyboardOptions = KeyboardOptions.Default.copy(
                            imeAction = ImeAction.Next
                        )
                    )
                }
                item {
                    Text(text = "Stock")
                    TextField(
                        value = if (state.stock == 0) "" else state.stock.toString(),
                        onValueChange = {
                            if (it.isDigitsOnly()) viewModel.onStockChange(if (it.isEmpty()) 0 else it.toInt())
                        },
                        keyboardOptions = KeyboardOptions.Default.copy(
                            keyboardType = KeyboardType.Number,
                            imeAction = ImeAction.Next
                        )
                    )
                }
                item {
                    Text(text = "Stock Maximo")
                    TextField(
                        value = if (state.stockMax == 0) "" else state.stockMax.toString(),
                        onValueChange = {
                            if (it.isDigitsOnly()) viewModel.onStockMaxChange(if (it.isEmpty()) 0 else it.toInt())
                        },
                        keyboardOptions = KeyboardOptions.Default.copy(
                            keyboardType = KeyboardType.Number,
                            imeAction = ImeAction.Next
                        )
                    )
                }
                item {
                    Text(text = "Stock Minimo")
                    TextField(
                        value = if (state.stockMin == 0) "" else state.stockMin.toString(),
                        onValueChange = {
                            if (it.isDigitsOnly()) viewModel.onStockMinChange(if (it.isEmpty()) 0 else it.toInt())
                        },
                        keyboardOptions = KeyboardOptions.Default.copy(
                            keyboardType = KeyboardType.Number,
                            imeAction = ImeAction.Next
                        )
                    )
                }
                if (showError) {
                    item {
                        Text(
                            text = "El Stock Mínimo no puede ser mayor que el Stock Máximo",
                            color = Color.Red
                        )
                    }
                }
                item {
                    Text(text = "Proveedor")
                    TextField(
                        value = state.proveedor,
                        onValueChange = { viewModel.onProveedorChange(it) },
                        keyboardOptions = KeyboardOptions.Default.copy(
                            imeAction = ImeAction.Next
                        )
                    )
                }
                item {
                    Text(text = "Email Proveedor")
                    TextField(
                        value = state.emailProveedor,
                        onValueChange = { viewModel.onEmailProveedorChange(it) },
                        keyboardOptions = KeyboardOptions.Default.copy(
                            keyboardType = KeyboardType.Email,
                            imeAction = ImeAction.Done
                        ),
                        keyboardActions = KeyboardActions(onDone = { /* Acciones al presionar "Enter" */ })
                    )
                }
                item {
                    Spacer(modifier = Modifier.height(20.dp))
                    Button(
                        onClick = {
                            viewModel.viewModelScope.launch {
                                viewModel.addProduct()
                                delay(200)
                                val lastProductId = viewModel.getLastProductId()
                                qrCodeGenerated = qrcodeGenerator(text = lastProductId.toString())
                                viewModel.hideForm()
                            }
                        },
                        modifier = Modifier.padding(bottom = 16.dp)
                    ) {
                        Text(text = "Agregar Producto")
                    }
                }
            }
        }
    }
}








fun qrcodeGenerator(text: String): Bitmap {
    val matrix = QRCodeWriter().encode(text, com.google.zxing.BarcodeFormat.QR_CODE, 512, 512)
    val w = matrix.width
    val h = matrix.height

    val bitmap = Bitmap.createBitmap(w, h, Bitmap.Config.RGB_565)

    for (y in 0 until h) {
        for (x in 0 until w) {
            bitmap.setPixel(
                x,
                y,
                if (matrix[x, y]) android.graphics.Color.BLACK else android.graphics.Color.WHITE
            )
        }
    }
    return bitmap
}
